### ISSUE TITLE
Database Compatibility

### ISSUE THREAD

**Issue by alexs131** [caledezma/WTdelineator#2]
Hi,
Will signal delineation only work for the STAFFIII database/can it be made adaptable for other databases on physionet as well?

**Comment by caledezma** [comment]
The delineator is a general signal processing scheme, therefore it should work fine in all ECG databases. At most, some constants would need to be adapted to account for changes in signal amplitude. If you have issues with other databases please let me know.

**Comment by yjshiki** [comment]
Hi, I've tested your method using QTDB, the delineator missed so many beats...
